# урок 7: МО_Генетика

ЗАДАНИЕ 1

Выбрать один из алгоритмов представленных по ссылке и реализовать его.
https://coderlessons.com/tutorials/akademicheskii/izuchite-geneticheskie-algoritmy/geneticheskie-algoritmy-krossover


In [1]:
from typing import Dict
from copy import deepcopy
from tqdm import tqdm

import random
import numpy as np
import pandas as pd
import xgboost as xgb

from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split
from IPython.display import clear_output

import seaborn as sns
import matplotlib.pyplot as plt

C:\Users\Windows\Anaconda3\lib\site-packages\dask\dataframe\utils.py:14: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


**Многоточечный кроссовер**

In [53]:
num_parents=8

features_count=5
number_of_parents_mating=4
parents = np.zeros((
        num_parents, features_count
    ))


parents[:, 0] = np.arange(1, 16, 2) #  max_depth column 
parents[:, 1] = np.arange(0, 8, 1) #  min_child_weight column
parents[:, 2] =  np.arange(0.01, 1, 0.14) #  subsample column
parents[:, 3] =  np.arange(0.01, 1, 0.14) #  colsample_bytree column
parents[:, 4] =  np.arange(0.01, 8, 1) #  gamma column

print(parents)
children_size=(num_parents,features_count)

[[1.00e+00 0.00e+00 1.00e-02 1.00e-02 1.00e-02]
 [3.00e+00 1.00e+00 1.50e-01 1.50e-01 1.01e+00]
 [5.00e+00 2.00e+00 2.90e-01 2.90e-01 2.01e+00]
 [7.00e+00 3.00e+00 4.30e-01 4.30e-01 3.01e+00]
 [9.00e+00 4.00e+00 5.70e-01 5.70e-01 4.01e+00]
 [1.10e+01 5.00e+00 7.10e-01 7.10e-01 5.01e+00]
 [1.30e+01 6.00e+00 8.50e-01 8.50e-01 6.01e+00]
 [1.50e+01 7.00e+00 9.90e-01 9.90e-01 7.01e+00]]


In [81]:
def crossover_many_points(parents, children_size):
    """
    Многоточечный кроссовер — это обобщение одноточечного кроссовера,
    в котором чередующиеся сегменты меняются местами для получения новых выходных пружин.
    """
    idx_1 = np.random.randint(
        0, np.uint8(children_size[1]), 1)[0]
    
    idx_2 = np.random.randint(
        0, np.uint8(children_size[1]), 1)[0]
    
    
    children = np.empty(children_size)
    
    print(idx_1)
    print(idx_2)
    

    for i in range(children_size[0]):
        parent1_idx = i % parents.shape[0]
        parent2_idx = (i+1) % parents.shape[0]
                
        for j in range(children_size[1]):
            if idx_1+1 < idx_2:
                if j <= idx_1 or j >= idx_2:
                    children[i, j] = parents[parent1_idx, j]
                else:            
                    children[i, j] = parents[parent2_idx, j]
            elif idx_2+1 < idx_1:
                if j <= idx_2 or j >= idx_1:
                    children[i, j] = parents[parent1_idx, j]
                else:            
                    children[i, j] = parents[parent2_idx, j]
            else:
                if j <= idx_2:
                    children[i, j] = parents[parent1_idx, j]
                else:            
                    children[i, j] = parents[parent2_idx, j]
            

    return children

In [82]:
crossover_many_points(parents, children_size)

1
4


array([[1.00e+00, 0.00e+00, 1.50e-01, 1.50e-01, 1.00e-02],
       [3.00e+00, 1.00e+00, 2.90e-01, 2.90e-01, 1.01e+00],
       [5.00e+00, 2.00e+00, 4.30e-01, 4.30e-01, 2.01e+00],
       [7.00e+00, 3.00e+00, 5.70e-01, 5.70e-01, 3.01e+00],
       [9.00e+00, 4.00e+00, 7.10e-01, 7.10e-01, 4.01e+00],
       [1.10e+01, 5.00e+00, 8.50e-01, 8.50e-01, 5.01e+00],
       [1.30e+01, 6.00e+00, 9.90e-01, 9.90e-01, 6.01e+00],
       [1.50e+01, 7.00e+00, 1.00e-02, 1.00e-02, 7.01e+00]])